version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/home/app
    ports:
      - "3000:3000"
    networks:
      - my-custom-network

networks:
  my-custom-network:
    external: true
